### ISSUE TITLE
List gets lost when updating data

### ISSUE THREAD

**Issue by johnnyluu** [davidroyer/vue2-editor#10]
I have this string defined in the vue data: 
```
<p><strong>Lorem Ipsum</strong></p>
 <p>This is a test blah blah blah</p>
 <ul>
 <li>LIst item 1</li>
 <li>List item 2</li>
 <li>List item 3</li>
 </ul>
```
when I do @editor-updated="handleContent"
//method
handleContent = funcion(value){this.content = value}

The returned value doesn't have the list in it: 
```
<p><strong>Lorem Ipsum</strong></p><p>
</p><p>This is a test blah blah blah</p><p>
</p><p>



</p>
```

Is it the plugin that's stripping the list out?

**Comment by davidroyer** [comment]
orry about the issues. I have updated Vue2Editor to 2.0 using v-model because of these same issues and it should resolve these problems. I'm closing this but let me know/reopen it if you have any other issues or questions.

**Comment by melirofman** [comment]
I am having the same issue. Did somebody find a way to fix it?

**Comment by melirofman** [comment]
@davidroyer

**Comment by macoshita** [comment]
This bug reproduces. ↓
https://codesandbox.io/embed/vue-template-pbluo

I fix it with the following PR↓
https://github.com/davidroyer/vue2-editor/pull/194

**Comment by macoshita** [comment]
@davidroyer

**Comment by sir-script** [comment]
@davidroyer It's still a bug. I've had the same issue like @ghost and @macoshita before. The pull request solves the issue. Could you take a look and check for any side effects? 
Thank you for offering such a great module.
Cheers,
Michael

**Comment by sir-script** [comment]
@davidroyer It looks like the problem occurs, when the text has some whitespace between the list items, like `<ul><li>Test</li>  some whitespace characters     <li>Link2</li></ul>`

**Comment by hoodist** [comment]
In my case, I used after changing like this.

**PHP**
`$html = preg_replace("/>\s+</","><", $html);`

I think you guys can be processing with regex even other language until it is resolved.
