### ISSUE TITLE
List of Custom Toolbar Options

### ISSUE THREAD

**Issue by dmerfeld** [davidroyer/vue2-editor#106]
Is there a master list of all the supported toolbar item names?

The Documentation example is great, but it would be helpful to know a full listing or a listing of those in use by default. 

I was able to guess alignment, but I'd like to know them all.

```javascript
data() {
        return {
          content: '',
          customToolbar: [
            ['bold', 'italic', 'underline'],
            [{ 'list': 'ordered'}, { 'list': 'bullet' }],
            [{ 'align': ''},{ 'align': 'justify'}, { 'align': 'right' }],
            ['link', 'video']
          ]
        }
      }
```

**Comment by humbugz** [comment]
It's not in the docs, but you can see it in the src: https://github.com/davidroyer/vue2-editor/blob/master/src/helpers/fullToolbar.js

> var fullToolbar = [
> [{ 'font': [] }],
>  [{ 'header': [false, 1, 2, 3, 4, 5, 6, ] }],
> [{ 'size': ['small', false, 'large', 'huge'] }],
> ['bold', 'italic', 'underline', 'strike'],
> [{'align': ''}, {'align': 'center'}, {'align': 'right'}, {'align': 'justify'}],
>  [{ 'header': 1 }, { 'header': 2 }],
>  ['blockquote', 'code-block'],
> [{ 'list': 'ordered'}, { 'list': 'bullet' }, { 'list': 'check' }],
> [{ 'script': 'sub'}, { 'script': 'super' }],
> [{ 'indent': '-1'}, { 'indent': '+1' }],
> [{ 'color': [] }, { 'background': [] }],
> ['link', 'image', 'video', 'formula'],
> [{ 'direction': 'rtl' }],
> ['clean'],
>]

**Comment by dmerfeld** [comment]
@humbugz thank you!

**Comment by hengseyha** [comment]
Could we have a table tool in it?

**Comment by aaron-ahmad** [comment]
![Untitled-1](https://user-images.githubusercontent.com/59386260/71818004-7c39f200-30a9-11ea-89e0-c063a5274d6e.jpg)

**Comment by aaron-ahmad** [comment]
![Capture](https://user-images.githubusercontent.com/59386260/71818024-8f4cc200-30a9-11ea-90c0-0853b349142b.jpg)

**Comment by alfligno** [comment]
Sad to say they dont provide how font works
