### ISSUE TITLE
how can I update the data ?

### ISSUE THREAD

**Issue by murilolivorato** [davidroyer/vue2-editor#13]
hello my friend . very nice code . Thanks for sharing with us .
I wold like to know how could I update like v-model="" , the data from the <vue-editor>
I saw that have this code @editor-updated="" .
Bit is not updating the data .

```
{{ description }}
 <vue-editor  :editor-content="description"  @editor-updated="description"  :use-save-button="false" > </vue-editor> 
```

I wold like to update the description , while I typing in the text area .
Am I making something wrong ?

Thanks

**Comment by davidroyer** [comment]
Sorry about the issues. I have updated Vue2Editor to 2.0 using v-model because of these same issues and it should resolve these problems. I'm closing this but let me know/reopen it if you have any other issues or questions. [Vue2Editor 2.0](https://github.com/davidroyer/vue2-editor)
