### ISSUE TITLE
Adding custom class to image embed

### ISSUE THREAD

**Issue by iulian34** [davidroyer/vue2-editor#132]
Hello, 
How can you add custom class to image that you are inserting in editor.
For exemple: 
```<img src="/image.jpg" class="image-css">```

``` Editor.insertEmbed(cursorLocation, 'image', url);```

**Comment by FreddyCrugger** [comment]
I have the same query, my images are not responsive using your editor and uploaded via the editor, any idea how to set a responsive class please? Thank you.

**Comment by iulian34** [comment]
You have the answer in documentation of Quill editor.

```
let Image = Quill.import('formats/image');
Image.className = 'your custom class here';
Quill.register(Image, true);
```
