### ISSUE TITLE
v-model doesn't update bound variable's data when text is paste in.

### ISSUE THREAD

**Issue by strongishllama** [davidroyer/vue2-editor#150]
When v-model is bound to a variables data and text is pasted into the editor, the bound variable does not update to include the changes from the paste. Once any other key is pressed, (ie. space, another character or delete) the variable is updated to include all the changes in the editor.

**Comment by lajosbencz** [comment]
Having the same issue, has anyone found a workaround to it?

**Comment by taliesinmillhouse** [comment]
No sorry.

**Comment by alatella87** [comment]
I can confirm having the same problem!!!!!

**Comment by vjee** [comment]
Ran into the same issue.

This is a quick and **dirty** work-around: (**pseudo code**)

```html
<template>
  <vue2-editor v-model="editorText" ref="editor">
</template>
```
```js
export default {
  data() {
    editorText: "",
  },
  mounted() {
    try {
      const Editor = this.$refs.editor;
      const $quillContainer = Editor.$refs.quillContainer;
      $quillContainer.onpaste = event => {
        const text = event.clipboardData.getData("Text");
        this.editorText = text;
      }
    } catch (e) {
      //
    }
  }
}
```

Explanation:

Whenever you paste text in the editor, a _paste_ event will be dispatched from the DOM.
If we listen to that event and extract the text, we can update the `v-model` property directly.

I wrapped the logic in a try/catch just for safety so we don't need to check every variable we use.

You can write a wrapper component around `vue2-editor` that does this and then calls `$emit('paste', text) so you can listen to it on your wrapper component and do something like `v-on:paste="text => editorText = text"`.
