### ISSUE TITLE
Cannot use v-on to listen to camelCase events when using in-DOM templates

### ISSUE THREAD

**Issue by Cealtea** [davidroyer/vue2-editor#152]
I cannot bind a listener from my html to imageAdded event because of the name of the event.
The event should be named image-added or imageadded, not imageAdded.
v-on:image-added would work.

From Vuejs 2 documentation
> Unlike components and props, event names will never be used as variable or property names in JavaScript, so there’s no reason to use camelCase or PascalCase. Additionally, v-on event listeners inside DOM templates will be automatically transformed to lowercase (due to HTML’s case-insensitivity), so v-on:myEvent would become v-on:myevent – making myEvent impossible to listen to.

**Comment by Cealtea** [comment]
Complete error in vue console: 
 Event "imageadded" is emitted in component <VueEditor> but the handler is registered for "imageAdded". Note that HTML attributes are case-insensitive and you cannot use v-on to listen to camelCase events when using in-DOM templates. You should probably use "image-added" instead of "imageAdded".

**Comment by ichuprov** [comment]
I had to edit the source files, changing imageAdded to image-added to make sure my event method was getting called.

**Comment by akserdin** [comment]
> I had to edit the source files, changing imageAdded to image-added to make sure my event method was getting called.

Yeah, I had to edit the source files also :)

**Comment by FlameFractal** [comment]
As this was a breaking change (_image handler not called, unless source file also edited_), I believe it should have been released with a warning or as a major release. @davidroyer

**Comment by ben-turner** [comment]
This change wasted 2 hours of my day today. The lack of detail in the release notes and the breaking change in a minor version bump definitely makes me wish I had used a different editor.
