### ISSUE TITLE
is it youtube support (iframe) ?

### ISSUE THREAD

**Issue by wahengchang** [davidroyer/vue2-editor#176]
we are running a EC platform, and many of the client would like to show their Youtube Video on Item Page. 

As I see, for now the toolbar and @event do have an interface for this achievement. We will need to implement it on cutome toolbar. 

Am I right? is there a easier way ?

**Comment by joonas1234** [comment]
I hope I understand your question correctly. Embedding video is supported and you only need to add 'video' as customToolbar option.
`customToolbar: [                    
    ['video'],
 ],`

**Comment by wahengchang** [comment]
perfect, it is what i need :)
