### ISSUE TITLE
Inline styles

### ISSUE THREAD

**Issue by andre-dw** [davidroyer/vue2-editor#18]
Is there someway to prevent the editor to add inline styles to html tags?

**Comment by davidroyer** [comment]
I believe this can be achieved by hooking into quill's api. Could you give a little more detail as to what you wanting to achieve? For example, if bold is selected, how would that get styled?

**Comment by andre-dw** [comment]
Sometime it adds inline styles to the tags like `style="color: black;"`. I just want it to add the tags like `<b>` or `<strong>` etc. 
The rest of the editor works great though!

**Comment by davidroyer** [comment]
The only way I was able to achieve this was by setting the color via the toolbar. Is this how you did it?
