### ISSUE TITLE
`lodash.merge` dependency is reported as a high severity security vulnerability

### ISSUE THREAD

**Issue by sxn** [davidroyer/vue2-editor#185]
`lodash.merge` is reported by [snyk](https://app.snyk.io/vuln/SNYK-JS-LODASHMERGE-173732) as a high severity security vulnerability

Would you consider replacing `lodash.merge` with the primary lodash package and fetching only the needed module? An example of this can be found [here](https://github.com/Akryum/v-tooltip/commit/d04ce8f99543ff67a2295912c58fb6e693c79ec3)

**Comment by davidroyer** [comment]
Thanks for closing this! I meant to since `lodash.merge` is no longer a dependency but obviously forgot.
