### ISSUE TITLE
Violation of DOM

### ISSUE THREAD

**Issue by nicolasvahidzein** [davidroyer/vue2-editor#189]
Hello, i get this error when using this component in my Vue JS project:

[Violation] Added synchronous DOM mutation listener to a 'DOMNodeInserted' event. Consider using MutationObserver to make the page more responsive.

**Comment by davidroyer** [comment]
What action is taking place when you see this error (adding content, removing content, etc)?

I'm pretty sure that error is from the actual Quill library and don't how to get it around it.

**Comment by nicolasvahidzein** [comment]
Oh ok, what a shame. I had to replace the package with toast UI. Sadly i can't answer that question. My apologies. I will close this issue. Cheers and thanks for your great work.
