### ISSUE TITLE
What if I don't want to inject css?

### ISSUE THREAD

**Issue by EnochG1** [davidroyer/vue2-editor#191]
version : 2.8.1

Hi,
I saw your dist code injects css like below and here's result.
![image](https://user-images.githubusercontent.com/19601207/59586312-99af6a80-911d-11e9-8177-bd6987246dae.png)
![image](https://user-images.githubusercontent.com/19601207/59586341-ad5ad100-911d-11e9-90b4-8d33976765a7.png)

But I want to make own theme and separate .css file for improving performance of webpack build.
So could you provide the option for it or make some guide for preventing inject quill's css code.

Thanks.

**Comment by davidroyer** [comment]
Hey!

I have been working on this and it will be available in 2.9 which should be released this week.

**Comment by EnochG1** [comment]
That's great. Thanks :)
