### ISSUE TITLE
How to getText() in vue2-editor

### ISSUE THREAD

**Issue by essivision** [davidroyer/vue2-editor#192]
Hi,
I need to `quill.getText()` function by [Official Document](https://quilljs.com/docs/api/#gettext). I didn't see any document about this. What should I do? 

Thanks

**Comment by davidroyer** [comment]
All of Quill's functionality referenced in their docs is available by providing the `VueEditor` component a `ref` attribute and then accessing `quill` from that reference.

**For example:**

``` html
<template>
  <div>
    <button @click="getEditorText">Get Text</button>
    <VueEditor ref="vEditor" v-model="content" />
  </div>
</template>

<script>
export default {
  data: () => ({
    content: ''
  }),

  methods: {
    getEditorText() {
      console.log(this.$refs.vEditor.quill.getText())
    }
  }
}
</script>
```
