### ISSUE TITLE
@focus @blur does not work

### ISSUE THREAD

**Issue by ITsolution-git** [davidroyer/vue2-editor#198]
I have installed latest version of vue2-editor@2.4.3. 
And I have issues now with focus and blur events.
These events are not firing. 
```
       <vue-editor
          v-model="course.description"
          :editorToolbar="customToolbar"
          :editorOptions="editorOptions"
          @focus="modified"
        />
```
Can you please check? Thank you!

**Comment by davidroyer** [comment]
The latest version is 2.9.1.
Try reinstalling and you should be good 👍.

https://www.npmjs.com/package/vue2-editor

<img width="1440" alt="latest-version" src="https://user-images.githubusercontent.com/8834693/61760257-f21afd00-ad98-11e9-93e3-cf374d360c3c.png">
