### ISSUE TITLE
Can I use it with chinese or other language ?

### ISSUE THREAD

**Issue by zuijiaoluo** [davidroyer/vue2-editor#2]

**Comment by evertramos** [comment]
Brazilian Portuguese maybe?

**Comment by davidroyer** [comment]
This is not a feature that is available through Quill that I am aware of.  Any ideas on implementing this?  I have no experience working with localization and other implementing other languages...

**Comment by evertramos** [comment]
@davidroyer I just got into to it and just noticed that what do we need is a Quill language implementation, so it´s no about vue2-editor. Thanks

**Comment by NingNingY** [comment]
when I use Chinese,there  is an extra letter in the head

**Comment by pua4pai** [comment]
like this ![demo.gif](http://www.z4a.net/images/2017/09/14/demo.gif)

**Comment by YujinGaya** [comment]
I'm using it with Korean and the first letter of every line crashes into its components, like 간 -> ㄱㅏㄴ.

**Comment by Shawn-Cui** [comment]
@pua4pai Have you solved this problem?

**Comment by Shawn-Cui** [comment]
@davidroyer This problem has been solved in quill v1.3.6, so would you please upgrade quill to v1.3.6?
