### ISSUE TITLE
Integration with extra modules

### ISSUE THREAD

**Issue by johnsoons** [davidroyer/vue2-editor#20]
Hello !!

Not a problem, but a possible solution to help other people.

**Come on!**

I was looking for an html editor and this one served very well.

I noticed that for the user to use images and want to resize it, he should do this work before uploading to the editor.

However, I would like to allow the user to perform this basic treatment through the editor, without needing another tool for this purpose.

With this, I found an implementation that performs exactly what I needed and with examples of how to integrate with Quill.

Https://github.com/kensnyder/quill-image-resize-module

In short, since I did not find a way to perform this integration, I implemented a solution for this, as follows:

**Props**
 
``` 
props: {
    value: String,
    id: {
        type: String,
        default: 'quill-container'
    },
    placeholder: String,
    disabled: Boolean,
    editorToolbar: Array,
    editorModules: Array // <<-
}
``` 

**Data**
```
data() {
    return {
        quill: null,
        editor: null,      
        modules: {
            toolbar: this.editorToolbar ? this.editorToolbar : defaultToolbar
        }      
    }
}
```

**Methods:**
```
methods: {
    initializeVue2Editor() {
        this.prepareModules() // <<-
        this.setQuillElement()
        this.setEditorElement()
        this.checkForInitialContent()
    },

    // ...
    prepareModules() {      
      if(this.editorModules !== undefined)
      {          
          let self = this
          this.editorModules.forEach(element => { 
            Quill.register('modules/' + element.alias, element.module)
            self.modules[element.alias] = element.config
          })
      }
    },
    // ...
}
```

Text translated by Google

**Comment by superbogy** [comment]
Well done~!

**Comment by pratikthakkar** [comment]
@johnsoons can you please share the complete code, a working example will really help.
thank you.

**Comment by davidroyer** [comment]
Integration is now available in the newest version 👍
