### ISSUE TITLE
How to fixed toolbar when scroll content

### ISSUE THREAD

**Issue by BiswasSuman** [davidroyer/vue2-editor#219]
To edit long content, I need to fixed toolbar at the top, I tried with some CSS code, it's working, but I am looking for, is there any inbuilt option for this?

**Comment by trungdnd** [comment]
i'm using css `position:sticky` for toolbar so it work, you can try
`.quillWrapper .ql-toolbar {
    position: -webkit-sticky;
    position: sticky;
    top: 0;
    z-index: 2;
    background-color: #fff;
}`

**Comment by FreddyCrugger** [comment]
you are the man, thanks!
