### ISSUE TITLE
how to change the image width when i want to upload image

### ISSUE THREAD

**Issue by iamsee** [davidroyer/vue2-editor#22]

**Comment by crabvn** [comment]
How do you upload image? I am using vue2editor but dont know how.

**Comment by manpenghui** [comment]
i have the same problem

**Comment by RuiguangZhao** [comment]
how can I edit the image I had uploaded?

**Comment by NGyc** [comment]
quill.clipboard.dangerouslyPasteHTML(range.index,'<img src='+item.image+' class=""><span>&nbsp</span>');
