### ISSUE TITLE
Cant implement inline style in any way

### ISSUE THREAD

**Issue by xxSkyy** [davidroyer/vue2-editor#220]
I'm trying to import BackgroundClass ColorClass and SizeStyle from quill but it dont want to work. 

How should I import those modules from Quill ?

**Comment by arantes555** [comment]
@xxSkyy 

```javascript
import { Quill, VueEditor } from 'vue2-editor'

const AlignClass = Quill.import('attributors/class/align')
Quill.register(AlignClass, false)
const BackgroundClass = Quill.import('attributors/class/background')
Quill.register(BackgroundClass, false)
const ColorClass = Quill.import('attributors/class/color')
Quill.register(ColorClass, false)
const FontClass = Quill.import('attributors/class/font')
Quill.register(FontClass, false)
const SizeClass = Quill.import('attributors/class/size')
Quill.register(SizeClass, false)
const AlignStyle = Quill.import('attributors/style/align')
Quill.register(AlignStyle, false)
const BackgroundStyle = Quill.import('attributors/style/background')
Quill.register(BackgroundStyle, true)
const ColorStyle = Quill.import('attributors/style/color')
Quill.register(ColorStyle, true)
const FontStyle = Quill.import('attributors/style/font')
Quill.register(FontStyle, true)
const SizeStyle = Quill.import('attributors/style/size')
Quill.register(SizeStyle, true)
```

**Comment by xxSkyy** [comment]
@arantes555 thank you, but I already figured it out ;) 
Here's my solution

First install quill by yourself then use that code :

`    import Quill from 'quill';
    import { VueEditor  } from "vue2-editor";


    let AlignStyle = Quill.import('attributors/style/align')
    let BackgroundStyle = Quill.import('attributors/style/background')
    let ColorStyle = Quill.import('attributors/style/color')
    let DirectionStyle = Quill.import('attributors/style/direction')
    let FontStyle = Quill.import('attributors/style/font')
    let SizeStyle = Quill.import('attributors/style/size')

    Quill.register(AlignStyle, true);
    Quill.register(BackgroundStyle, true);
    Quill.register(ColorStyle, true);
    Quill.register(DirectionStyle, true);
    Quill.register(FontStyle, true);
    Quill.register(SizeStyle, true);`
