### ISSUE TITLE
How do I upload image?

### ISSUE THREAD

**Issue by crabvn** [davidroyer/vue2-editor#23]
I would like to upload the image to server then editor only render the uploaded image.

**Comment by numens** [comment]
I have also encountered the same problem

**Comment by core45** [comment]
I think it's rather Quill itself problem but I'd love to be able to process image on the server too...

**Comment by davidroyer** [comment]
I just added this feature last night. If you check out the [README]( https://github.com/davidroyer/vue2-editor), I have updated it to include some info about this new feature.
