### ISSUE TITLE
Warning log initialize

### ISSUE THREAD

**Issue by amaglione** [davidroyer/vue2-editor#257]
Hi!! 

When i load the component of my app thar import de vue2-editor, I've got the next warning:

![image](https://user-images.githubusercontent.com/1660116/81512044-f26a9180-92f3-11ea-865f-0ddf3353a78f.png)

Can anybody help me?

**Comment by papalardo** [comment]
How you importing the component ? Paste u code

**Comment by amaglione** [comment]
Hi!! 

I have a component called "Editor" which has the next code:

import VueEditor from 'vue2-editor'

export default {
  components: {
    VueEditor
  },
  data() {
    return {
        content:"",
        customToolbar: [ [{ font: [] }], 
                         [{ size: ["small", false, "large", "huge"] }],
                          [
                                { align: "" },
                                { align: "center" },
                                { align: "right" },
                                { align: "justify" }
                            ],
                         ["bold", "italic", "underline"], [{ list: "ordered" }, { list: "bullet" }], ["image", "code-block"]]
    };
  }
};

**Comment by papalardo** [comment]
Try import like
```js
import { VueEditor } from "vue2-editor";
```
Instead
```js
import VueEditor from "vue2-editor";
```

**Comment by amaglione** [comment]
Mmm nothing, still have the same error. The input seems to work fine but the console log that error...

**Comment by papalardo** [comment]
I cant reproduce the error

Can you reproduce in [CodeSandbox](https://codesandbox.io/s/vue) ?

**Comment by amaglione** [comment]
I solved it. I have in my index.html a `
<script src="https://unpkg.com/vue2-editor/dist/vue2-editor.umd.min.js"></script>` 

Thanks!!

**Comment by papalardo** [comment]
Cool. Please, mark issue like close.
