### ISSUE TITLE
How can I style the code-block by highlightjs?

### ISSUE THREAD

**Issue by dphans** [davidroyer/vue2-editor#26]
I used to using QuillJS.
I love that because I can custom editor by my self.
But I can I access Quill core? Can I apply hightlightjs styles into editor?

**Comment by eserdinyo** [comment]
Hi. Is this issue solved? I also can't do this.

**Comment by eserdinyo** [comment]
Ok. I guess i solved it finally. 
I added this 
`<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js"></script>`
in the index.html.

And it's done.
