### ISSUE TITLE
how can i change rgb color code to hex color code

### ISSUE THREAD

**Issue by leehan0617** [davidroyer/vue2-editor#262]
I want to change rgb color to hex color code.
example:  
`<strong style="rgb(255, 153, 0)">blur blur</strong>  => <strong style="color: #ff9900;">blur blur</strong>
`
because, android os can't read rgb color

**Comment by Alexander-Bliznyuk** [comment]
### Possible solutions

#### A simple one

```html
<vue-editor :editorToolbar="editorToolbar"></vue-editor>
```

```javascript
export default {
    data()  {
        return {
            editorToolbar: [
                [
                    {color: ["red", "green", "blue"]},
                    {background: ["red", "green", "blue"]}
                ],
            ],  
        };
    },
}
```

#### A more elegant
```javascript
    import {Quill} from 'vue2-editor';

    const color = Quill.import('formats/color');
    const background = Quill.import('formats/background');

    function addRawColorProperty(node, value) {
        if (!this.canAdd(node, value)) return false;
        node.style[this.keyName] = '';  //clear previously set color to avoid stacking
        node.setAttribute(
            'style',
            (node.getAttribute('style') || '') + `${this.keyName}: ${value};`
        );
        return true;
    }

    color.add = background.add = addRawColorProperty;

    Quill.register({
        'formats/color': color,
        'formats/background': background,
    });

```

### Here is the explanation
The problem lays in how browsers process color strings. 
https://developer.mozilla.org/en-US/docs/Web/CSS/color
> If the value is translucent, the computed value will be the rgba() corresponding one. If it isn't, it will be the rgb() corresponding one.

Quill's `color` and `background`  formatters inherit [this method](https://github.com/quilljs/parchment/blob/master/src/attributor/style.ts#L22) which writes  to CSSStyleDeclaration object where every color string, with the exception of mnemonics, ends up computed i.e. in rgb or rgba form.

**Comment by leehan0617** [comment]
Thanks for comment. I solve this problem using regex.
