### ISSUE TITLE
How to use it by using server render?

### ISSUE THREAD

**Issue by dupeiduo** [davidroyer/vue2-editor#28]
ReferenceError: document is not defined

**Comment by karthikvt26** [comment]
Hi,

Is this fixed? I am also facing this issue.

**Comment by dupeiduo** [comment]
@karthikvt26  Not yet.

**Comment by Lahori-Jawan** [comment]
any progress?

**Comment by davidroyer** [comment]
Vue2Editor doesn't currently support SSR.  You'll need to wait until in the browser process/on the client.

If you are using Nuxt.js, there are a few easy ways to configure the settings so that it works perfectly. Reopen this issue if this is case and you need assistance.

**Comment by gokhancetiner** [comment]
> Vue2Editor doesn't currently support SSR. You'll need to wait until in the browser process/on the client.
> 
> If you are using Nuxt.js, there are a few easy ways to configure the settings so that it works perfectly. Reopen this issue if this is case and you need assistance.

Hello,

Thanks for great module !!!

Do you have any plans to support SSR in the near future? 

Many Thanks
