### ISSUE TITLE
How do I insert a link?

### ISSUE THREAD

**Issue by QinFeiFei** [davidroyer/vue2-editor#29]
<img> or text add <a link="">

**Comment by QinFeiFei** [comment]
`<a link>`

**Comment by gowdaabhishek1990** [comment]
I was wondering too. How do I add links?

**Comment by gowdaabhishek1990** [comment]
@QinFeiFei You can provide 'link' in your customtoolbar config, in the src code this is not there. For more configuration options you can look into quill configuration

**Comment by xiliubianbian** [comment]
I was wondering too. How do I add links?

**Comment by xiliubianbian** [comment]
I found a solution. 
Add an array in the editorToolbar of component , the contents of array is link .

**Comment by edobacon** [comment]
I did that, but it needs to write the 'http://' to work, if i just write, google.com, it looks for localhost/google.com... is there a way to fix/change this behavior to google.com => http://google.com ?

**Comment by davidroyer** [comment]
Write it like this:
`//google.com`
