### ISSUE TITLE
add imageResize

### ISSUE THREAD

**Issue by ktmswzw** [davidroyer/vue2-editor#37]
[VueEditor.vue.zip](https://github.com/davidroyer/vue2-editor/files/1310832/VueEditor.vue.zip)
[ImageResize.js.zip](https://github.com/davidroyer/vue2-editor/files/1310834/ImageResize.js.zip)

...
modules: {
          toolbar: this.toolbar,
          imageResize: {
            displaySize: true
          }
        },
.....

**Comment by pratikthakkar** [comment]
this looks more like a quill solution, rather then a plugin solution ?

**Comment by davidroyer** [comment]
Custom Module implementation is available now
[See it in New Docs](https://davidroyer.github.io/vue2-editor/#/?id=how-to-use-custom-quill-modules)
