### ISSUE TITLE
How do i add tables?

### ISSUE THREAD

**Issue by mmanishh** [davidroyer/vue2-editor#372]
Is there any modules where i can use tables in editor? I tried https://www.npmjs.com/package/quill-table-ui but it requires quill 2.0

**Comment by tylerlmn** [comment]
Nobody can help?

**Comment by Skintillion** [comment]
Make a PR to update quill on this repo to 2 then add your table module

**Comment by mmanishh** [comment]
@Skintillion Seems like Quill v2.0 is still in development mode. It has not released yet. https://github.com/quilljs/quill/tree/v2.0.0-dev.0 Closing this for now
