### ISSUE TITLE
How to full screen

### ISSUE THREAD

**Issue by kingyangmeng** [davidroyer/vue2-editor#38]
it can full screen ??
I need full screen editor，i do not  know  how full screen .
Could you tell me how to set it full screen .

--from China

thank you ....

**Comment by sir-script** [comment]
@davidroyer Could you explain, why you closed the issue? 
It would be a nice feature in a form window, when there is not much space left for the editor...
Are there any plans to develop this feature?  Or how would you do that in our case?

Thank you in advance and for building this gorgeous editor. :)
