### ISSUE TITLE
v2.10.3 custom css for toolbar

### ISSUE THREAD

**Issue by soulincsl** [davidroyer/vue2-editor#383]
I can't style the toolbar color as I want

**Comment by c-engineer** [comment]
Probably not the best solution but this works... 

wrap the vue2-editor component in a div with a unique class name, then target each class inside the div. 

Toolbar color you could do this:
``
.text-editor . card-header {
background-color: #F00;
color: #FFF;
}
``

Toolbar buttons:
``
.text-editor .card-header .btn-outline-dark {
color: #FFF;
border: 1px solid #FFF;
}

.text-editor .card-header .btn-outline-dark:hover {
color: #F00;
background-color: #FFF;
border: 1px solid #FFF;
}
``

Border under the toolbar:
``
.text-editor .card .border-dark {
border-color: #F00 !important;
}
``

`` .text-editor `` being the unique class
