### ISSUE TITLE
useCustomImageHandler prop still set to false

### ISSUE THREAD

**Issue by changefox** [davidroyer/vue2-editor#45]
Hi I can't get the custom image handler to trigger currently;

Template (inline)
` <vue-editor
  id="os-answer-textarea-new"
  useCustomImageHandler
  @imageAdded="handleImageAdded"
  v-model="answer">
</vue-editor>`

JS (i removed some of the other stuff and note that axios is already added to the project

`

import { VueEditor } from 'vue2-editor'

Vue.component('os-help', {
  
    props: ['user' , 'currentTeam'],
  
    components: {
        VueEditor
    },
  
    data() {
        
        return {

          answer: '',
          
        };
    },

    created() {
        //
    },

    mounted() {
        //
    },
  
    computed: {
      
    },
  

    filters: {
    },
  
    watch: {      

    },
  
    methods : {
      
     handleImageAdded: function(file, Editor, cursorLocation) {
        // An example of using FormData
        // NOTE: Your key could be different such as:
        // formData.append('file', file)
       
        alert('we got an image!');
      },

    }
  
});
`
Any help would be great

**Comment by jaskiratr** [comment]
@changefox  Were you able to resolve this?

**Comment by changefox** [comment]
No I didn’t. I ended up creating the “edit” page without Vue.js

…

Regards,

Chris Winfield-Blum
Founder & CEO

[cflogo_02_150w]<http://www.changefox.com/>

How would you rate your experience with Change Fox?<http://www.changefox.com/provide-us-feedback>

**Comment by davidroyer** [comment]
I am unable to recreate the issue. I'm going to close this issue but if this is something you would still like to figure out then feel free to reopen it. If you reopen it, any additional info such as the error you are getting, ect would be helpful.

**Comment by jsam6** [comment]
This can be solved using@image-added instead on @imageAdded
[#250](https://github.com/davidroyer/vue2-editor/issues/250)

**Comment by outman** [comment]
`:use-custom-image-handler="true"`
[https://vuejs.org/v2/guide/components-props.html](https://vuejs.org/v2/guide/components-props.html)
`HTML attribute names are case-insensitive, so browsers will interpret any uppercase characters as lowercase. That means when you’re using in-DOM templates, camelCased prop names need to use their kebab-cased (hyphen-delimited) equivalents:`
