### ISSUE TITLE
There is bound editor-content, but the editor does not show the value.

### ISSUE THREAD

**Issue by clown-doll** [davidroyer/vue2-editor#5]
There is bound editor-content, but the editor does not show the value.
Vue.js devtools also shows that editorContent has a value.
I was calling like this:
`<VueEditor
						:editor-content="htmlForEditor"
						:use-save-button="false"
						@editor-updated="handleUpdatedContent">
					</VueEditor>`
And in the created hook to get the data, set the value of htmlForEditor.

Just try to use the click event to assign.
If the assignment is displayed (like this: `this.htmlForEditor = 'Html For Editor'`) it succeeds, but if the value is dynamic (like this: `this.htmlForEditor = this.content`), it will not display successfully .

**Comment by davidroyer** [comment]
Thank you for brining this to my attention.

I have updated it both here on NPM accordingly. Please let me know if you find it working correctly now or are still having issues.

Thanks!

**Comment by clown-doll** [comment]
Content can come out, but it is unresolved and appears directly like this: `<p> test</ p>`

**Comment by davidroyer** [comment]
What do you mean by unresolved and strange phenomenon?

**Comment by clown-doll** [comment]
What I would expect is something like this:
![2](https://cloud.githubusercontent.com/assets/12654989/22632162/e9dee742-ec51-11e6-918e-e6782ecd61c4.png)

But it is like this:
![1](https://cloud.githubusercontent.com/assets/12654989/22632158/e4073126-ec51-11e6-95bf-53eea76b1e9b.png)

I'm sorry, my English is very poor. Now I have a clear expression?
