### ISSUE TITLE
Importing Fonts

### ISSUE THREAD

**Issue by re1naldo** [davidroyer/vue2-editor#50]
How to import additional fonts to the toolbar? I read on [this page](http://quilljs.com/playground/#custom-fonts) that we need to use Quill object. How to do this using vue2-editor?

**Comment by riksnelders** [comment]
Same problem here, found a solution yet?

**Comment by MarkGStacey** [comment]
Was there a solution to this?

**Comment by riksnelders** [comment]
Dont think so. Switched to ckeditor
