### ISSUE TITLE
choosing default option from toolbar

### ISSUE THREAD

**Issue by eybarta** [davidroyer/vue2-editor#55]
Hey, thanks for your work.

I'd like to have a 'direction' option in the toolbar which
I easily added in the toolbar options, BUT I'd like to have
it ON by default (direction 'rtl')... 
I think with Quill I could use the Quill.format('direction', 'rtl') method..
Could you expose the format method in your plugin or explain how I would
set a default value to a formatting option?

thanks!

**Comment by aebrs** [comment]
I need the same option too.
