### ISSUE TITLE
Independen component in the same page

### ISSUE THREAD

**Issue by lmatab** [davidroyer/vue2-editor#58]
Thanks for the component.

I try to create two independent component but it looks like the second one overwrites the another.

How can use this component several times in the same page but in a independent way?

Greetings

**Comment by davidroyer** [comment]
There’s an example of this in the README. Each instance of the editor needs a unique id attribute.
![e77386f6-48cb-46a1-be7b-4de2a2dbba58](https://user-images.githubusercontent.com/8834693/35295446-2fe75bb6-0047-11e8-9a4f-11bd1d826155.png)
