### ISSUE TITLE
Extending functionality using the Quill API

### ISSUE THREAD

**Issue by wcarron27** [davidroyer/vue2-editor#6]
Hey, this doesn't really count as an issue, but it's something I was wondering:

In the native Quill RTE, they provide a highly extensible API. For example, they have documentation showing how to implement a 'word-count' plugin/extension to the editor. In vue2-editor, is there an interface which enables me to write the extensions/plugins? Or am I able to drop down to the internal guts of Quill.js and do this? Would love to know your thoughts on this and potentially contribute if that's on the roadmap.

**Comment by japhfortin** [comment]
+1
