### ISSUE TITLE
How to set or enable Quill module?

### ISSUE THREAD

**Issue by krisnaw** [davidroyer/vue2-editor#60]
Hi there, 
Is there a way to set or enable quill module? I'd like to enable matchVisual modules.  https://quilljs.com/docs/modules/clipboard/#matchvisual

**Comment by davidroyer** [comment]
In the next release (which will be out within a few days) this functionality will be available.

**Comment by davidroyer** [comment]
This is now possible in the new version.

**Comment by LouqG** [comment]
could you provide an example please?
