### ISSUE TITLE
Please remove axios

### ISSUE THREAD

**Issue by Romick2005** [davidroyer/vue2-editor#61]
Hi David,

Good job!!!
One thing that bother me is axios in package.json.
It scare me as it seems that package can send some data outside using axios.
As far as I can see it is used only in examples so I guess it could be easily replaced with cdn link for examples https://cdnjs.cloudflare.com/ajax/libs/axios/0.17.1/axios.js. This will also remove extra unneeded dependency on axios.
Thanks.

**Comment by davidroyer** [comment]
Axios is now only a devDependency
