### ISSUE TITLE
Reactive props

### ISSUE THREAD

**Issue by VRuzhentsov** [davidroyer/vue2-editor#62]
What if i want to provide to textarea some reactive placeholder? If it possible to use quill for it, and I need to make pull request for this feature, or I need to find another plugin?

**Comment by davidroyer** [comment]
Could you elaborate on this? I’m not sure I understand what your scenario is/what you’re asking.

**Comment by temyer** [comment]
I use [vue-i18n](https://kazupon.github.io/vue-i18n/) and put placeholder prop in computed property:
`editorPlaceholder() {
  return this.$t('common.yourMessage');
},`
In vue Dev tools prop to vue2-editor changes, however it does not change in component, unless i refresh a page.

**Comment by VRuzhentsov** [comment]
1.5 year pass. I don't remember where is a concern.
Maybe I feel some problems with get/set & computed
when used them with this editor
