### ISSUE TITLE
It can not add tag <div> to content

### ISSUE THREAD

**Issue by Aoqidx** [davidroyer/vue2-editor#63]
My code is show as follow:
![selection_012](https://user-images.githubusercontent.com/17473416/35387659-9127a460-020b-11e8-848f-0c18ef5d8c97.jpg)
If content is '&lt;h1&gt;Some initial content&lt;/h1&gt;', editor can show 'Some initial content' correctly, but when content is '&lt;div&gt;Some initial content&lt;/div&gt;', editor throw a error "Cannot read property 'emit' of undefined"
![selection_011](https://user-images.githubusercontent.com/17473416/35387777-17269e68-020c-11e8-940f-a162c8a29b50.jpg)

**Comment by davidroyer** [comment]
Hmmm you’re right. I’ll be looking into this asap.

**Comment by davidroyer** [comment]
After some research, it’s looks like Quill converts <div> tags to <p> tags.

**Comment by davidroyer** [comment]
@Aoqidx, if you update to the latest version, you shouldn't see this error anymore.

**Comment by baixiaoji** [comment]
@davidroyer  I having the same problem, in the version 2.4.2

**Comment by assuncaojr** [comment]
@davidroyer same problem here, version: 2.4.3

**Comment by storkyle** [comment]
@davidroyer I'm having the same problem, in the version 2.5.0 :( 
Help me, please! :'(

**Comment by mintsoda** [comment]
@davidroyer I'm having the same problem, 
in the version 2.5.0 too
Help me, please! :'(

**Comment by hlohrenz** [comment]
Same problem as well. I can't get past this.

**Comment by asitwala** [comment]
Affected by this as well (using version 2.6.6), but I was able to bypass it by referencing this post: [https://github.com/quilljs/quill/issues/861](https://github.com/quilljs/quill/issues/861)

We’re essentially changing the Quill Editor to use ‘div’ blocks by default. So my code looks like: 

```
import { VueEditor, Quill } from 'vue2-editor';

const Block = Quill.import('blots/block');
Block.tagName = 'DIV';
Quill.register(Block, true);
```

Hope this might help others temporarily!

**Comment by arrchi-style** [comment]
How about insert some html into content? If insert simple div it works. But if you want to add something like this <div><h1>TEST</h1></div> it add only div

**Comment by sobancodes** [comment]
This issue still exists in 2.9.0 and in the latest version. I don't know why it is closed especially when the workaround introduces more bugs. I just wasted so much time working with this library. :/

**Comment by KiritoXF** [comment]
Here is my solution:
```
import { Quill } from 'vue-quill-editor'
const BlockEmbed = Quill.import('blots/block/embed')

class CustomBlot extends BlockEmbed {
  static create (obj) {
    let node = super.create()
    const customContainer = document.createElement('div')
    // use appendChild to append some tags you want to customContainer
    // such as hr, label, input
    // ...
    node.appendChild(customContainer)
  }
  static value (domNode) {
    return domNode
  }
}
CustomBlot.blotName = 'customTagName'
CustomBlot.tagName = 'customTagName'
```
Just set `blotName` and `tagName` to a custom string, render the tag in CustomBlot's create function.
And it will render like:
```
<customTagName>
  <div>
    // some other tag appended before
  </div>
</customTagName>
```

Although i'm use vue-quill-editor rather than vue2-editor, they both based on Quilljs. So maybe this will help others.
