### ISSUE TITLE
Is there a way to make the editor be focused

### ISSUE THREAD

**Issue by yang-andy-YANG** [davidroyer/vue2-editor#64]
For example, the editor is hidden at somewhere of the page , I click on a button, that makes the editor visible, for a better user experience,  the editor is better to be focused at the same time, any way for this?

**Comment by davidroyer** [comment]
Yes I believe you could find something in the Quill.js docs.  If you do find something and feel like it needs to be/would be nice if it was integrated into Vue2Editor, let me know.

I plan to look into this as well.

**Comment by yang-andy-YANG** [comment]
Yes, it is true,  Quill has api to focus the editor, I do see quill instance is exposed as a  property, by calling the api of this quill instance, focus could be implemented.

Thanks

**Comment by YevheniiHerasymchuk** [comment]
https://github.com/yang-andy-YANG
How did you solve this problem?

**Comment by yang-andy-YANG** [comment]
@YevheniiHerasymchuk 
Below is the html code:
  <vue-editor v-model.trim="content.desc" useCustomImageHandler @imageAdded="handleImageAdded" class="editor" :editorToolbar="customToolbar" :placeholder="$t('communityList.fill_in_the_detail')" **ref="editor"**></vue-editor>

And js code to focus:
**this.$refs.editor.quill.focus()**

**Comment by yash-india** [comment]
i have tried the above solution but it's not working.
