### ISSUE TITLE
 the customized image handler is only called once when I upload the same images multiple times

### ISSUE THREAD

**Issue by yang-andy-YANG** [davidroyer/vue2-editor#65]
I  have already set up the prop "useCustomImageHandler" and event 'imageAdded',  the first time I upload the image, the event is triggered correctly. BUT the event will NOT be called if I upload the same image again. 

Best Regards,
Yang

**Comment by davidroyer** [comment]
Does it work when the 2nd image is different or does that fail as well?

**Comment by yang-andy-YANG** [comment]
It works fine if a different image is uploaded

**Comment by davidroyer** [comment]
This is fixed in the most recent release.

The issue was needing to reset the value of the file uploader input.

Because of this, `resetUploader` is now emitted along with the other parameters when the `imageAdded` event is emitted. It's a function that you execute after inserting the image like so:
```javascript
Editor.insertEmbed(cursorLocation + 1, 'image', url);
resetUploader();
```
See the [updated example](https://davidroyer.github.io/vue2-editor/#/?id=example-custom-image-handler) in the Docs

**Comment by webylb** [comment]
The cursor does not change the position after the custom image is uploaded.
How to make it normal?

**Comment by webylb** [comment]
I found a way through the console Editor.
getSelection(), setSelection()
Document needs to be updated, Thank you ever so much.

**Comment by ays-code** [comment]
> This is fixed in the most recent release.
> 
> The issue was needing to reset the value of the file uploader input.
> 
> Because of this, `resetUploader` is now emitted along with the other parameters when the `imageAdded` event is emitted. It's a function that you execute after inserting the image like so:
> 
> ```js
> Editor.insertEmbed(cursorLocation + 1, 'image', url);
> resetUploader();
> ```
> 
> See the [updated example](https://davidroyer.github.io/vue2-editor/#/?id=example-custom-image-handler) in the Docs

Hi.
I can't get the example to work. The same behavior.
The link with the updated example is lost.

Thanks.
