### ISSUE TITLE
Using with Nuxt in SSR

### ISSUE THREAD

**Issue by Lahori-Jawan** [davidroyer/vue2-editor#66]
Although I have only imported and registered in components and not declared inside template but reloading the page prompts the error:
```
NuxtServerError

render function or template not defined in component: anonymous
```

doesn't it pose bad UX impression? BTW, how can I use it in Nuxt?

**Comment by Lahori-Jawan** [comment]
@davidroyer can you help me on this?

**Comment by davidroyer** [comment]
@Lahori-Jawan 
Registering the plugin with the `ssr: false` should fix any issues. 

***Example in the Nuxt.js Docs: https://nuxtjs.org/examples/plugins/***

Does this fix the issue? If not, do you have a repo I can look at?

**Comment by Lahori-Jawan** [comment]
Thanks! Its working now. 

for your information: I just noticed that your `README.md` has duplicate `Development` and `License` declaration.

**Comment by davidroyer** [comment]
@Lahori-Jawan 
Fantastic!

Also, thanks for letting me know about the README. 👍

**Comment by ald890** [comment]
@Lahori-Jawan Hello, can you show your example how you solve this issue?

**Comment by Lahori-Jawan** [comment]
create a file inside `plugins` directory i.e. `quill-editor.js` and paste this in:
```
import Vue from "vue";
import { VueEditor } from "vue2-editor";

Vue.use(VueEditor);
```
now in your `nuxt.config.js` include this plugin i.e.
```
module.exports = {
     // head: {  //  },
    plugins: [
		{ src: "~plugins/quill-editor.js", ssr: false },
	]
}
```
and now you can just follow the docs to use in `.vue` file

**Comment by jaskiratr** [comment]
Hello @Lahori-Jawan 
How did you include the component in the `.vue` file. I'm receiving the following error
`[Vue warn]: Unknown custom element: <VueEditor> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

Any thoughts?

**Comment by jaskiratr** [comment]
Ah, I had to register the component!

```js
// quill-editor.js
import Vue from "vue"
import { VueEditor } from "vue2-editor"

// Vue.use(VueEditor, {name: 'vue-editor'})
Vue.component('vue-editor', VueEditor)
```
