### ISSUE TITLE
File size reduction

### ISSUE THREAD

**Issue by Yorgovan** [davidroyer/vue2-editor#69]
Can file size be smaller? Or can we exclude some features that we don't need?

It is pretty big compared to other modules. It is even bigger than vue itself and jquery.

Here you can see it with webpack bundle analyzer
![vue2-editor-size](https://user-images.githubusercontent.com/33957795/36308378-bd7d878e-1320-11e8-8eb7-2841ec39adeb.png)

**Comment by davidroyer** [comment]
@Yorgovan 

This is because vue2-editor includes Quill and it's minified file is over 200kb.

**Comment by galaczi** [comment]
I am using vue2-editor with Nuxt. My problem is that it's added globally in the vendors bundle but it's only used in the admin area of the app. How could I import it only when it's needed and not add it globally to the project?
