### ISSUE TITLE
Content defined in component data is not rendered as html when first loaded

### ISSUE THREAD

**Issue by johnnyluu** [davidroyer/vue2-editor#8]
So I have this component:
```
<template>
  <div class="page">
  	<h2>Homepage</h2>
  	<vue-editor
      :editor-content="content" @editor-updated="handleContent">
    </vue-editor>
    <div class="preview" v-html="content"></div>
  </div>
</template>

<script>
import {VueEditor} from 'vue2-editor';
export default {
  name: 'pages',
  data () {
    return {
      content: '<h1>Hello</h1>'
    }
  },
  components: { VueEditor },
  methods: {
    handleContent: function (value) {
      this.content = value;
    }
  }
}
</script>
```
When the page loads, the editor's content is `<h1>Hello</h1>` showing as a string, instead of <h1>Hello</h1> as a heading. If I update the content in a method or after 'mounted' event, the content displays fine. Is it a bug? Or am I doing something wrong here?

**Comment by davidroyer** [comment]
This was actually a bug.  I have updated the code so if you want to run npm update in your local working director, it should work as expected now.

My apologies for the inconvenience! I'm going to close this but feel free to let me know if you have any other issues!

**Comment by johnnyluu** [comment]
Thanks David, I'll give it another try today.
