### ISSUE TITLE
quill Overwriting modules/markdownShortcuts with ƒ t(e,n){var o=this;r(this,t),this.quill=e,this.options=n,this.matches=[{name:"header",pattern:/^(#){1,6}\s/g,action:function(t,e){switch(t.trim()){case"#":o.quill.formatLine(e.index,0,"header",1);brea…

### ISSUE THREAD

**Issue by chiaweilee** [davidroyer/vue2-editor#82]
A warn display in console when from a router to another router which contain editor..

> quill Overwriting modules/markdownShortcuts with ƒ t(e,n){var o=this;r(this,t),this.quill=e,this.options=n,this.matches=[{name:"header",pattern:/^(#){1,6}\s/g,action:function(t,e){switch(t.trim()){case"#":o.quill.formatLine(e.index,0,"header",1);brea…vue2-editor.js?391e:1 
-- | -- | --
  | value | @ | vue2-editor.js?391e:1
  | registerBuiltInModules | @ | vue2-editor.js?391e:1
  | prepareModules | @ | vue2-editor.js?391e:1
  | initializeVue2Editor | @ | vue2-editor.js?391e:1
  | mounted | @ | vue2-editor.js?391e:1
  | callHook | @ | vue.esm.js?06e7:2923
  | insert | @ | vue.esm.js?06e7:4143
  | invokeInsertHook | @ | vue.esm.js?06e7:5954
  | patch | @ | vue.esm.js?06e7:6173
  | Vue._update | @ | vue.esm.js?06e7:2672
  | updateComponent | @ | vue.esm.js?06e7:2790
  | get | @ | vue.esm.js?06e7:3144
  | run | @ | vue.esm.js?06e7:3221
  | flushSchedulerQueue | @ | vue.esm.js?06e7:2983
  | (anonymous) | @ | vue.esm.js?06e7:1839
  | flushCallbacks | @ | vue.esm.js?06e7:1760

This happened when router switched only, nothing will report if refresh this page.

**Comment by charleslck** [comment]
mark,same problem...

**Comment by zchar-hong** [comment]
mark,same problem...

**Comment by shuhankuang** [comment]
mark,same problem...

**Comment by ZhelinCheng** [comment]
mark,same problem...

**Comment by ggiotopoulos** [comment]
same issue. 
I'm noticing something that may stem from this. My editor comes up empty when this warning happens even when something should be there.

**Comment by ashenwolf** [comment]
Same problem :( Are there any updates on this? Maybe there's some kind of temporary workaround at least?

**Comment by promyaaa** [comment]
Same problem and after route change the default content is `<p><br></p>`. Now whatever text you insert in the textarea you get `<p><br></p>`.

**Comment by gmferreir1** [comment]
mark,same problem...

**Comment by PedroLopesMV** [comment]
Mark, same problem. The first time it shows the warning, but after a page refresh, it doesn't show up anymore.

**Comment by kreso10** [comment]
I had same error with multiple and single editor per page after switching routes. Adding 'id' solved my problems (even with single one on page).

**Comment by kem709394** [comment]
mark,same problem...

**Comment by davidroyer** [comment]
Fixed in v2.4.4. Includes Merged Pull Request #100.
