### ISSUE TITLE
How can I add custom formats to Quill?

### ISSUE THREAD

**Issue by elceka** [davidroyer/vue2-editor#84]
I have a custom format for Quill editor, but registration doesn't work (Quill.register(ClassName, true)).
Please, can you make a example for implementation of custom formats? Or is needed to make implementation for registration of format process to the component?

**Comment by elceka** [comment]
Import of Parchment doesn't work, import of it by Quill working good.

**Comment by jwhitmarsh** [comment]
@elceka would you be able to provide an example of how you got this to work?
