### ISSUE TITLE
Cannot read property 'index' of null

### ISSUE THREAD

**Issue by Beenheed** [davidroyer/vue2-editor#87]
I get 
"Uncaught TypeError: Cannot read property 'index' of null" - vue2-editor.js?698a:1
if I use the default underline (`<u></u>`) or the the default strikethrough (`<s></s>`) 

Bold or italic work fine. 

I am using the most basic version without any extra quill options.

**Comment by EugeneHerasymchuk** [comment]
Did you have multiple editors on the page? 
It could be triggered by this case
