### ISSUE TITLE
Content can't be edited after updated

### ISSUE THREAD

**Issue by johnnyluu** [davidroyer/vue2-editor#9]
After pulling the latest version, the html content defined in data is rendering fine. However, after the vue data is updated, it can't be edited again because the cursor doesn't appear when I click on the text area.

**Comment by davidroyer** [comment]
Hey, I have updated it again. Tested it for loading data on mount and then making sure it is editable. Let me know if it works as expected for you as well.

**Comment by davidroyer** [comment]
Hey, Vue2Editor has been updated to 2.0 to use v-model and should resolve this issue.
