### ISSUE TITLE
Is there a way to save it Temporary to cookies?

### ISSUE THREAD

**Issue by weituotian** [davidroyer/vue2-editor#99]
when i leave this component,  later and  i return to it.
will i saw the same i edit before?

**Comment by Grantimus9** [comment]
No, unless you add logic to save. You can save to localstorage easily: localStorage.setItem('bgcolor', 'red'); https://developer.mozilla.org/en-US/docs/Web/API/Storage/setItem. 

This library does not automatically save works in progress.

**Comment by weituotian** [comment]
@Grantimus9 
when i could save the content from editor?
